### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(SimpleFog)
add_subdirectory(SimpleFogContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	SimpleFogplugin
	SimpleFogContentplugin)