### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(CarRendering)
add_subdirectory(CarRenderingContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	CarRenderingplugin
	CarRenderingContentplugin)